name: Alert about super-submodule reference differences

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: inkarkat/git-extensions@master
