name: Alert about superproject↔submodule reference differences

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          submodules: recursive
          fetch-depth: 0
      - uses: inkarkat/git-supersubinout@master
